name: Scrape latest data

on:
  # push:
  workflow_dispatch:
  schedule:
    # 2:10 am Pacific Time
    - cron: '10 9 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    #- name: Fetch latest data
    #  run: |-
    #    curl https://www.theguardian.com/science/rss >gsci.rss
    # sqlite-utils --csv feeds.db "select title,link,updated from links order by updated desc;"  >gscience.csv

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feed-to-sqlite
        pip install sqlite-utils
    - name: Fetch latest data
      run: |-
        feed-to-sqlite feeds.db --table links https://www.theguardian.com/science/rss 
        feed-to-sqlite feeds.db --table links https://feeds.bbci.co.uk/news/science_and_environment/rss.xml?edition=us
        sqlite-utils --csv feeds.db "select title,link,published from links;"  >gscience.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
